### ISSUE TITLE
Newsweek review

### ISSUE THREAD

**Issue by eliasecasta** [SajjadAhmad14/Newsweek-Clone#1]
Hello Sajjad, your mobile view looks nice, try to use this to fix the other views:

- col-(size from 1-12) ex col-12
- Add all the content to featured stories (finish the mobile view first before jumping to the other ones)
- Don't forget semantics.
 
Good luck Sajjad, keep it going!

**Comment by SajjadAhmad14** [comment]
Thank you, Elias. You always rais good points while reviewing my code! Done!
