### ISSUE TITLE
Newsweek review

### ISSUE THREAD

**Issue by eliasecasta** [SajjadAhmad14/Newsweek-Clone#2]
Hello Sajjad, you are almost thereeeeeee!

- Your main problem is that you are nesting rows inside rows, be careful with that and try to read a little bit more about bootstrap grid, your structure should be container>row>col>divs.
- Try to correct your structure because weird things start to happen when you nest things too much in bootstrap.

**Comment by SajjadAhmad14** [comment]
Thanks for the review! Done!
