### ISSUE TITLE
Review 7/6/2020

### ISSUE THREAD

**Issue by eliasecasta** [SajjadAhmad14/Newsweek-Clone#6]
Hello Sajjad, good job, you almost break my record! Hahaha

Small tips for your recent review:

- Use the container fluid for your navbar container instead of the navbar class from bootstrap
- For some reason you are applying space between in the search and icon elements, you need to apply the space between to the container of all that navbar, not to the 3 items (maybe your HTML structure is wrong here)
- Apply more border radius to the debate section and make them smaller
- In the subscribe section, in the desktop view the only thing that I can see that you are missing is the gray color should surround both, the image and the text with button, also make the text and button a little more to the left and in the mobile view center the elements

Good luck!

**Comment by SajjadAhmad14** [comment]
Thank you for pointing out issues, team. Done!
